version: '3.8'

services:
  ui:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - 80:80
    environment:
      NODE_ENV: development